<p style="color:green;font-weight:700;font-size:25px; text-align: center;"> Cape Lookout National Seashore Place Connections and Changing Weather and Environmental Conditions for Future Planning and Preservation</p>

<p style="color:green;font-weight:500;font-size:16px; text-align: center;"> Online Survey for Members of Partner Organizations, March 2024 </p>
<p style="color:green;font-weight:500;font-size:16px; text-align: center;"> Project Title: Examining Diverse Management Objectives and Broadening Stakeholder Engagement for Climate Adaptation Planning of Historic Structures Stewarded by the National Park Service</p>
<p style="color:green;font-weight:400;font-size:13px; text-align: center;"> Principal investigator (PI): Dr. Erin Seekamp, Goodnight Distinguished Professor  </p> 
<p style="color:green;font-weight:400;font-size:13px; text-align: center;"> Director, NC State Coastal Resilience and Sustainability Initiative, College of Natural Resources, NC State University </p>
<p style="color:green;font-weight:400;font-size:13px; text-align: center;"> Phone: 919.513.7407; Email: elseekam@ncsu.edu </p>

<p style="color:green;font-weight:400;font-size:13px; text-align: center;"> Developed by: Dr. Abu Kibria, NC State University </p>
<p style="color:green;font-weight:400;font-size:13px; text-align: center;"> April 16, 2024 </p>


In [1]:
import pandas as pd

In [3]:
#import original data
part_org_dt= pd.read_csv('Partner_org_Sur_apr 6-24.csv', skiprows=[0,2])
part_org_dt.head()

Start Date             End Date Response Type     IP Address  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43    IP Address  104.28.32.199   
1  2024-01-27 19:59:36  2024-01-27 20:14:00    IP Address  98.121.26.227   
2  2024-01-27 20:49:31  2024-01-27 21:10:40    IP Address    107.12.9.39   
3  2024-01-27 21:21:20  2024-01-27 22:18:03    IP Address  107.12.12.209   
4  2024-01-28 06:46:54  2024-01-28 07:14:28    IP Address  104.28.32.177   

   Progress  Duration (in seconds)  Finished        Recorded Date  \
0       100                   4389      True  2024-01-27 19:38:44   
1       100                    864      True  2024-01-27 20:14:01   
2       100                   1268      True  2024-01-27 21:10:41   
3       100                   3403      True  2024-01-27 22:18:04   
4       100                   1653      True  2024-01-28 07:14:29   

         Response ID  Recipient Last Name  ...  \
0  R_506I2X8dp8Wg8oS                  NaN  ...   
1  R_7dK8urLQAtxsiDn                  NaN  ...   
2  R_6KoNYz72KMGLtXr                  NaN  ...   
3  R_7Ph3en9FYEuc1oW                  NaN  ...   
4  R_6yzHAs6UJq9dZ1D                  NaN  ...   

   8.3 In what year did you last visit Cape Lookout National Seashore?  \
0                                             2023.0                     
1                                             2005.0                     
2                                             2023.0                     
3                                             2023.0                     
4                                             2023.0                     

   8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Cape Lookout Lighthouse area of Cape Lookout Village  \
0                                 More than 12 times                                                                                                                                                                                                 
1                                            0 times                                                                                                                                                                                                 
2                                            6 times                                                                                                                                                                                                 
3                                 More than 12 times                                                                                                                                                                                                 
4                                             1 time                                                                                                                                                                                                 

   8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Other areas of Cape Lookout Village (Coast Guard Station & summer cottages area)  \
0                                           10 times                                                                                                                                                                                                                             
1                                            0 times                                                                                                                                                                                                                             
2                                            0 times                                           

In [5]:
# find the list of columns
list(part_org_dt.columns)

['Start Date',
 'End Date',
 'Response Type',
 'IP Address',
 'Progress',
 'Duration (in seconds)',
 'Finished',
 'Recorded Date',
 'Response ID',
 'Recipient Last Name',
 'Recipient First Name',
 'Recipient Email',
 'External Data Reference',
 'Location Latitude',
 'Location Longitude',
 'Distribution Channel',
 'User Language',
 '1.1 From which organization did you receive the email with a link to this survey? (Please select one choice)',
 '1.2 What is your membership status within the following Cape Lookout partner organizations? (You must select a response for both organizations before the survey will allow you to go to the next page) - Core Sound Waterfowl Museum & Heritage Center',
 '1.2 What is your membership status within the following Cape Lookout partner organizations? (You must select a response for both organizations before the survey will allow you to go to the next page) - Friends of Portsmouth Island',
 '1.3 Which of the following historic areas are you most connected t

In [7]:
# Replace the column names with shorter ones
part_org_dt.rename(columns = {                    
 'Start Date': 'start_date',
 'End Date': 'end_date',
 "Duration (in seconds)": 'duration(sec.)',
 "1.1 From which organization did you receive the email with a link to this survey? (Please select one choice)": "organization",
 "1.2 What is your membership status within the following Cape Lookout partner organizations? (You must select a response for both organizations before the survey will allow you to go to the next page) - Core Sound Waterfowl Museum & Heritage Center": "member_stat_cswmhc",
 "1.2 What is your membership status within the following Cape Lookout partner organizations? (You must select a response for both organizations before the survey will allow you to go to the next page) - Friends of Portsmouth Island": "member_stat_fpi",
 "1.3 Which of the following historic areas are you most connected to at Cape Lookout National Seashore? (Please select one choice)": "hist_most_conn",
 "1.4 Which of the following recreation areas are you most connected to at Cape Lookout National Seashore? (Please select one choice)": "rec_most_conn",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - a. I feel CALO is a part of me.": "calo_part_me",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - b.  I identify strongly with CALO.": "ident_calo_strong",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - c. What happens at CALO doesn't matter to me.": "dosnt_matter_calo",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - d. No other place can compare to CALO.": "calo_uncompare",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - e. Few people know CALO like I do.": "few_know_calo_lkme",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - f. My family's income or livelihood depends on CALO.": "fam_livhood_calo",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - g. Many important family memories are tied to CALO.": "fam_memry_calo",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - h. Local communities' history is strongly tied to CALO.": "comm_hist_calo",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - i. The local economy depends on CALO.": "locl_econ_calo",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - j. CALO is an important part of our history as a nation.": "imp_nation_hist",
 "2.1 We are interested in knowing more about your connections and local communities’ connections to CALO generally (not just a specific historic district or area). \nPlease indicate your level of agreement or disagreement with each of the following statements. (Please select one choice for each statement below) - k. Preserving the history and culture associated with historic buildings at CALO is important for future generations.": "imp_futr_gen",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - a. ...contributes to the character of local communities.': "char_locl_comm",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - b. ...provides feelings of community pride.': "feel_comm_prd",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - c. ...creates a stronger sense of community togetherness.': "comm_together",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - d. ...makes it a special place for my family.': "spec_plc_fam",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - e. ...provides me with a sense of pride in my heritage.': "my_hert_prid",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - f. ...provides a sense of family bonds in local communities.': "fam_bond_locl_comm",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - g. ...attracts tourism dollars to local communities.': "toursm_incm",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - h. ...contributes to a more stable local economy.': "stabl_locl_econ",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - i. ...is unique and unlike other historic barrier island communities in the region.': "uniq_his_reg",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - j. ...contributes to the uniqueness of local communities.': "uniq_locl_comm",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - k. ...holds important stories of the past.': "imp_stry_past",
 '3.1 We are interested in knowing more about the potential benefits of the history and culture at CALO.\n\n \nPlease indicate your level of agreement or disagreement with each of the following statements.\n\n(Please select one choice for each statement below)\n\n..stands for "The history and culture associated with CALO" - l. ...has important interpretive values to communicate stories to visitors.': "imp_interptv_commnica",
 "4.1 How have the recent changes (since 2018) affected your family's connections to CALO?(Please slide the button for each statement below) - a. Ability to access the historic districts.": "accessibility",
 "4.1 How have the recent changes (since 2018) affected your family's connections to CALO?(Please slide the button for each statement below) - b. Proportion of historic buildings remaining.": "hist_bld_rem",
 "4.1 How have the recent changes (since 2018) affected your family's connections to CALO?(Please slide the button for each statement below) - c. Ability to learn about the history and culture.": "ablty_lrn_hist",
 "4.1 How have the recent changes (since 2018) affected your family's connections to CALO?(Please slide the button for each statement below) - d. Ability to recreate in areas traditionally used.": "ablty_rec_trd_area",
 "4.1 How have the recent changes (since 2018) affected your family's connections to CALO?(Please slide the button for each statement below) - e. All changes experienced.": "all_chng_expr",
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Accessing historic villages\n\n(a). Being able to visit anytime I want\n\n(access>75% time of the year due to flooding or dock damage)": 'visit_>75%_yr',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Accessing historic villages\n\n(b). Being able to visit most of the time I want\n\n(access about 50% of the year due to flooding or dock damage)": 'visit_~50%_yr',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Accessing historic villages\n\n(c). Not being able to visit very often\n\n(access <25% of the year due to flooding or dock damage)": 'visit_<25%_yr',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Accessing historic districts\n\n(d). Not being able to visit the historic districts at all\n\n(no access)": 'no_accss',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Buildings remaining\n\n(a). Seeing most of the buildings\n\n(>75% remain from those in 2018) in the landscape": '>75%_bld_rem_fr2018',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Buildings remaining\n\n(b). Seeing some of the buildings\n\n(~50% remain from those in 2018) in the landscape": '~50%_bld_rem_fr2018',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Buildings remaining\n\n(c). Seeing only a few buildings\n\n(<25% remain from those in 2018) in the landscape": '<25%_bld_rem_fr2018',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Buildings remaining\n\n(d). Seeing no buildings\n\n(0% remain) in the landscape": 'no_bld_rem_fr2018',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Learning\n\n(a). Being able to visit Harkers Island (Park Visitor Center or Core Sound Museum) and learn about the historic districts through photos, panels, and/or movies": 'visit_hrkrs_lrn_hdist_ph&v',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Learning\n\n(b). Being able to visit Harkers Island (Park Visitor Center or Core Sound Museum) and learn about the stories of the people who lived in the buildings through photos, panels, voice recordings, and/or movies": 'visit_hrkrs_lrn_ppl_ph&v',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Learning\n\n(c). Being able to visit Harkers Island (Park Visitor Center or Core Sound Museum) and learn about the historic districts through virtual reality (3D headset of the Village as it is in 2025)": 'visit_lrn_hdist_vr',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Learning\n\n(d). Being able to read about the stories of the people who lived in the buildings in a book": 'lrn_ppl_bk',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Landscape\n\n(a). Ability to recreate in most places traditionally used\n\n(>75% areas unchanged)": 'recr>75%_unchng',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Landscape\n\n(b). Moderate ability to recreate in traditional areas \n\n(~50% of areas unchanged)": 'recr~50%_unchng',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Landscape\n\n(c). Limited ability to recreate in areas traditionally used\n\n(<25% of areas unchanged)": 'recr<25%_unchng',
 "4.2 How might future changes impact your family's connection to CALO.\n\n(Please select slide the button for each statement below) - Landscape\n\n(d). No ability to recreate in areas traditionally used\n\n(0% of landscape unchanged)": 'recr_no_unchng',
 '4.3 Please indicate how important the following factors are in influencing your family\'s connections to either or both of the historic districts at CALO.\n\n\n\nFor example, if you think that "access" is extremely important but you think that the proportion of buildings is not at all important; then you would move the slider as far to the "access" side.\n\n(Please slide the button between each choice below.)': 'bld_rem vs visit_accss',
 "Q9a": 'bld_rem vs lrn_bld',
 "Q9b": 'vist_accss vs lrn_bld',
 "Are you interested in answering the questions about future management of historic buildings?\n\nIf you answer no, you will go to the final page in the survey.\n\nIf you answer yes, there are 4 additional pages in the survey.": 'cons_mgt_bld_surv',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - a. Oral Histories:\n\npreparing for loss by extensively documenting the stories of the people who last lived in the districts (or visited people living in the districts)": 'oral_hist_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - Actions - move a to b and b to a": 'empty',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - b. High Tech Virtual Experiences:\n\npreparing for loss by extensively documenting the historic villages with 3D scanning of structures and drone videos": 'high_tech_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - c. Elevating Structures:\n\nadapting structures by elevating them to reduce flooding impacts (6-8 feet)": 'elev_st_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - d. Moving Structures:\n\nadapting structures by moving them to higher ground within the historic village (limited space where “moderately” vulnerable instead of “severely” vulnerable, and may need to be elevated after moved)": 'mov_st_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - e. On-Site Barriers:\n\nadding sea walls around structures to reduce the damage from waves and erosion": 'swall_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - f. Using Resilient Building Materials:\n\nno longer using historic materials but more resilient materials that can reduce the damage from waves, erosion, and wind": 'use_res_mat_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - g. Removing Parts of Structures:\n\nactively removing floors and additions to reduce the damage from waves, erosion and wind": 'remv_prt_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - h. Letting Go:\n\nallowing structures to decay (become “relics” on the landscape) on the landscape rather than continued investment in historic preservation": 'let_go_calo',
 "5.1 To what extent do you agree or disagree with the following types of approaches to deal with changing weather and environmental conditions at Cape Lookout National Seashore:\n\n(Please select one choice for each statement below) - i. Removing Structures:\n\nactively removing structures rather than continued investment in historic preservation": 'remv_st_calo',
 "Storm-related actions\n\nA challenge is that storms could create damage that may result in the loss of more buildings in any given year. Although we know that storms are becoming more frequent and more severe, we can’t predict when one will be as damaging as or worse than Hurricanes Florence or Dorian.\n\n \n\n5.2 Which of the following types of actions do you think managers should also be taking now:\n\n(Please select one choice for each statement below) - a. Post-storm Recovery: fully recovering a building with historic materials": 'now_pstm_rcvr_calo',
 "Storm-related actions\n\nA challenge is that storms could create damage that may result in the loss of more buildings in any given year. Although we know that storms are becoming more frequent and more severe, we can’t predict when one will be as damaging as or worse than Hurricanes Florence or Dorian.\n\n \n\n5.2 Which of the following types of actions do you think managers should also be taking now:\n\n(Please select one choice for each statement below) - b. Post-storm Retention: only restoring the exterior footings, walls, and roof and removing interior elements and additions (porches) to better withstand the next storm event.": 'now_pstm_ret_calo',
 "5.3 Which of the following types of actions do you think managers should also be taking beginning around 2035 (10 years from now):\n\n(Please select one choice for each statement below) - a. Post-storm Recovery: fully recovering a building with historic materials": '2035_pstm_rcvr_calo',
 "5.3 Which of the following types of actions do you think managers should also be taking beginning around 2035 (10 years from now):\n\n(Please select one choice for each statement below) - b. Post-storm Retention: only restoring the exterior footings, walls, and roof and removing interior elements and additions (porches) to better withstand the next storm event." :'2035_pstm_ret_calo',
 "5.4 Which of the following types of actions do you think managers should also be taking beginning around 2045 (20 years from now):\n\n(Please select one choice for each statement below) - a. Post-storm Recovery: fully recovering a building with historic materials": '2045_pstm_rcvr_calo',
 "5.4 Which of the following types of actions do you think managers should also be taking beginning around 2045 (20 years from now):\n\n(Please select one choice for each statement below) - b. Post-storm Retention: only restoring the exterior footings, walls, and roof and removing interior elements and additions (porches) to better withstand the next storm event.": '2045_pstm_ret_calo',
 "5.5 Please indicate the extent to which you prefer the the following approaches to handling future storm impacts?\n\n(Please slide the button toward the choice your prefer, or keep it in the center if you prefer them equally.) - 1": 'pstm_recvr vs pstm_retn',
 "6.1 Please indicate which of these the following approaches do you prefer now?\n\n(Please slide the button toward the choice your prefer, or keep it in the center if you prefer them equally.) - 1": 'prsrv_fulnds vs adpt_fulnds',
 "Q16a - 1": 'prsrv_fulnds vs trns_fulnds',
 "Q16b - 1": 'adpt_fulnds vs trns_fulnds',
 "6.2 Please indicate which of these the following approaches do you prefer beginning around 2035 (10 years from now)?\n\n(Please slide the button toward the choice your prefer, or keep it in the center if you prefer them equally.) - 1": '2035 prsrv_fulnds vs adpt_fulnds',
 "Q17a - 1": '2035 prsrv_fulnds vs trns_fulnds',
 "Q17b - 1": '2035 adpt_fulnds vs trns_fulnds',
 "6.3 Please indicate which of these the following approaches do you prefer beginning around 2045 (20 years from now)?\n\n(Please slide the button toward the choice your prefer, or keep it in the center if you prefer them equally.) - 1": '2035 prsrv_fulnds vs adpt_fulnds',
 "Q18a - 1": '2045 prsrv_fulnds vs trns_fulnds',
 "Q18b - 1": '2045 adpt_fulnds vs trns_fulnds',
 "6.4 With the exception of the Lighthouse, do you think any historic buildings will remain on the landscape at 2045?": 'excpt_lhs_any_other_45',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Accessing historic districts\n\n(a). Being able to visit most anytime I want\n\n(accessible >75% time of the year due to flooding or dock damage)": 'stp_invst_accss>75%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Accessing historic districts\n\n(b). Being able to visit most of the time I want\n\n(accessible about 50% of the year due to flooding or dock damage)": 'stp_invst_accss~50%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Accessing historic districts\n\n(c). Not being able to visit very often\n\n(accessible <25% of the year due to flooding or dock damage)": 'stp_invst_accss<25%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Accessing historic districts\n\n(d). Never being able to visit\n\n(no access)": 'stp_invst_accss_no',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Buildings remaining\n\n(a). Seeing most of the buildings\n\n(>75% remain from those in 2018) in the landscape": 'stp_invst_rem>75%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Buildings remaining\n\n(b). Seeing some of the buildings\n\n(~50% remain from those in 2018) in the landscape": 'stp_invst_rem~50%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Buildings remaining\n\n(c). Seeing only a few buildings\n\n(<25% remain from those in 2018) in the landscape": 'stp_invst_rem<25%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Storm impacts\n\n(a). Most of the buildings are considered destroyed following a storm\n\n(>75% of buildings are destroyed)": 'stp_invst_dest>75%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Storm impacts\n\n(b). About half of the buildings are considered destroyed following a storm\n\n(~50% of buildings are destroyed)": 'stp_invst_dest~50%',
 "7.1 Looking ahead in the future, the National Park Service would like to know your opinions about decision points in which the National Park Service should stop investment in maintaining the historic buildings. \n\n \n\nPlease state the extent to which you disagree or agree with the following decision points when the National Park Service should stop investing in the maintenance of the historic buildings at Cape Lookout National Seashore.\n\n(Please select sldie the button for each statement below) - Storm impacts\n\n(c). A few of the buildings are considered destroyed following a storm\n\n(<25% of buildings are destroyed)": 'stp_invst_dest<25%',
 "8.1 In what year were you born?\n(Please scroll to the correct year)": 'b_yr',
 "8.2 In what year did you first visit Cape Lookout National Seashore?": '1st_vist_yr',
 "8.3 In what year did you last visit Cape Lookout National Seashore?": 'last_vist_yr',
 "8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Cape Lookout Lighthouse area of Cape Lookout Village": 'vist_freq12_lths_cv',
 "8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Other areas of Cape Lookout Village (Coast Guard Station & summer cottages area)": 'vist_freq12_pv',
 "8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Portsmouth Village": 'vist_freq12_pv',
 "8.4 How many times have you visited the following historic districts on Cape Lookout National Seashore in the past 12 months? \n\n(Please scroll to the number for each statement below) - Other areas": 'vist_freq12_other',
 "8.5 Have you or your family ever owned, or occupied through a lease, buildings at either Portsmouth Island or Lookout Village? \n(Please select one and add a year, such as 1998 or 2010, when appropriate) - Selected Choice": 'own_occup_les',
 "8.5 Have you or your family ever owned, or occupied through a lease, buildings at either Portsmouth Island or Lookout Village? \n(Please select one and add a year, such as 1998 or 2010, when appropriate) - Not me but my relatives have\n\n(please indicate in which year your family last occupied the building) - Text": 'my_rltv_own',
 "8.5 Have you or your family ever owned, or occupied through a lease, buildings at either Portsmouth Island or Lookout Village? \n(Please select one and add a year, such as 1998 or 2010, when appropriate) - Yes\n\n(please indicate in which year you last occupied the structure) - Text": 'yes_we_own',
 "8.6 What is your primary Zip code? \n(please enter the five-digit postal code for the address at which you spend the most time each year)": 'zip_prim',
 "8.7 If you have a secondary address near Cape Lookout National Seashore, what is that Zip code? \n(please enter the five-digit postal code for the vacation or rental property you own near Cape Lookout National Seashore)": 'zip_secd'}, inplace=True)

part_org_dt.head()


start_date             end_date Response Type     IP Address  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43    IP Address  104.28.32.199   
1  2024-01-27 19:59:36  2024-01-27 20:14:00    IP Address  98.121.26.227   
2  2024-01-27 20:49:31  2024-01-27 21:10:40    IP Address    107.12.9.39   
3  2024-01-27 21:21:20  2024-01-27 22:18:03    IP Address  107.12.12.209   
4  2024-01-28 06:46:54  2024-01-28 07:14:28    IP Address  104.28.32.177   

   Progress  duration(sec.)  Finished        Recorded Date        Response ID  \
0       100            4389      True  2024-01-27 19:38:44  R_506I2X8dp8Wg8oS   
1       100             864      True  2024-01-27 20:14:01  R_7dK8urLQAtxsiDn   
2       100            1268      True  2024-01-27 21:10:41  R_6KoNYz72KMGLtXr   
3       100            3403      True  2024-01-27 22:18:04  R_7Ph3en9FYEuc1oW   
4       100            1653      True  2024-01-28 07:14:29  R_6yzHAs6UJq9dZ1D   

   Recipient Last Name  ...  last_vist_yr  vist_freq12_lths_cv  \
0                  NaN  ...        2023.0   More than 12 times   
1                  NaN  ...        2005.0              0 times   
2                  NaN  ...        2023.0              6 times   
3                  NaN  ...        2023.0   More than 12 times   
4                  NaN  ...        2023.0               1 time   

       vist_freq12_pv      vist_freq12_pv  vist_freq12_other  \
0            10 times  More than 12 times           10 times   
1             0 times             0 times            0 times   
2             0 times             0 times            6 times   
3  More than 12 times             0 times            0 times   
4             2 times             2 times             1 time   

                                       own_occup_les my_rltv_own yes_we_own  \
0                                                 No         NaN        NaN   
1                                                 No         NaN        NaN   
2                                                 No         NaN        NaN   
3  No but I have visited people when they lived t...         NaN        NaN   
4  No but I have visited people when they lived t...         NaN        NaN   

  zip_prim zip_secd  
0    27019      NaN  
1    27603  28524.0  
2    28516      NaN  
3    28516      NaN  
4    27253      NaN  

[5 rows x 119 columns]

In [9]:
#exclude unnecessary columns
part_org_dt= part_org_dt.loc[:, ~part_org_dt.columns.isin([
 'Response Type',
 'IP Address',
 'Progress',
 'Finished',
 'Recorded Date',
 'Response ID',
 'Recipient Last Name',
 'Recipient First Name',
 'Recipient Email',
 'External Data Reference',
 'Location Latitude',
 'Location Longitude',
 'Distribution Channel',
 'User Language',
 'empty'])]
part_org_dt.head()

start_date             end_date  duration(sec.)  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653   

                        organization member_stat_cswmhc member_stat_fpi  \
0  Friends of Portsmouth Island only       Not a member  Current member   
1  Friends of Portsmouth Island only     Current member  Current member   
2  Friends of Portsmouth Island only     Current member  Current member   
3  Friends of Portsmouth Island only       Not a member    Not a member   
4  Friends of Portsmouth Island only     Current member  Current member   

                                      hist_most_conn  \
0                                 Portsmouth Village   
1  Both Portsmouth Village and Cape Lookout Villa...   
2  The Coast Guard and Summer Cottages Area of Ca...   
3  The Cape Lookout Lighthouse Area of Cape Looko...   
4                                 Portsmouth Village   

                                       rec_most_conn    calo_part_me  \
0           All of the recreation areas listed above           Agree   
1  I don't feel connected to any of the recreatio...           Agree   
2                                  Shackleford Banks  Strongly agree   
3                                         Core Banks  Strongly agree   
4                                  Portsmouth Island           Agree   

  ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv      vist_freq12_pv  \
0             Agree  ...       2023.0  More than 12 times            10 times   
1             Agree  ...       2005.0             0 times             0 times   
2    Strongly agree  ...       2023.0             6 times             0 times   
3    Strongly agree  ...       2023.0  More than 12 times  More than 12 times   
4             Agree  ...       2023.0              1 time             2 times   

       vist_freq12_pv vist_freq12_other  \
0  More than 12 times          10 times   
1             0 times           0 times   
2             0 times           6 times   
3             0 times           0 times   
4             2 times            1 time   

                                       own_occup_les my_rltv_own yes_we_own  \
0                                                 No         NaN        NaN   
1                                                 No         NaN        NaN   
2                                                 No         NaN        NaN   
3  No but I have visited people when they lived t...         NaN        NaN   
4  No but I have visited people when they lived t...         NaN        NaN   

  zip_prim zip_secd  
0    27019      NaN  
1    27603  28524.0  
2    28516      NaN  
3    28516      NaN  
4    27253      NaN  

[5 rows x 104 columns]

In [11]:
# list of all missing values in 'organization' columna
part_org_dt[part_org_dt['organization'].isna()]


start_date             end_date  duration(sec.) organization  \
15   2024-01-27 18:55:05  2024-01-27 18:55:14               8          NaN   
16   2024-01-27 19:04:05  2024-01-27 19:05:08              63          NaN   
17   2024-01-27 23:10:51  2024-01-27 23:11:05              13          NaN   
18   2024-01-28 08:01:49  2024-01-28 08:02:41              52          NaN   
193  2024-02-04 18:39:11  2024-02-04 18:44:52             341          NaN   
209  2024-02-06 08:03:58  2024-02-06 08:05:08              69          NaN   
212  2024-02-06 08:18:36  2024-02-06 08:19:00              24          NaN   
215  2024-02-06 08:30:21  2024-02-06 08:30:32              11          NaN   
218  2024-02-06 08:31:56  2024-02-06 08:35:52             236          NaN   
219  2024-02-06 08:34:52  2024-02-06 08:36:53             120          NaN   
221  2024-02-06 09:13:22  2024-02-06 09:23:20             598          NaN   
226  2024-02-06 10:07:48  2024-02-06 10:12:36             288          NaN   
233  2024-02-06 13:36:30  2024-02-06 13:41:56             326          NaN   
234  2024-02-06 14:08:21  2024-02-06 14:08:33              11          NaN   
237  2024-02-06 09:01:44  2024-02-06 16:02:23           25238          NaN   
238  2024-02-06 16:56:55  2024-02-06 16:59:10             135          NaN   
241  2024-02-06 20:42:03  2024-02-06 20:43:20              76          NaN   
268  2024-02-07 10:15:20  2024-02-07 12:02:53            6452          NaN   
270  2024-02-07 12:26:23  2024-02-07 12:26:50              27          NaN   
294  2024-02-08 13:43:01  2024-02-08 13:43:10               9          NaN   
302  2024-02-10 08:06:46  2024-02-10 08:10:05             199          NaN   
303  2024-02-10 08:09:21  2024-02-10 08:12:26             185          NaN   
307  2024-02-10 10:10:43  2024-02-10 10:10:56              13          NaN   
310  2024-02-10 10:34:51  2024-02-10 10:42:24             452          NaN   
315  2024-02-10 12:12:42  2024-02-10 12:13:51              68          NaN   
324  2024-02-10 16:59:06  2024-02-10 17:02:48             222          NaN   
326  2024-02-10 18:37:03  2024-02-10 18:37:27              24          NaN   
329  2024-02-10 22:33:02  2024-02-10 22:34:10              68          NaN   
333  2024-02-11 06:39:18  2024-02-11 09:40:14           10856          NaN   
337  2024-02-11 14:33:30  2024-02-11 14:36:45             195          NaN   
338  2024-02-11 14:36:52  2024-02-11 14:37:37              44          NaN   
340  2024-02-11 18:06:05  2024-02-11 18:09:19             194          NaN   
345  2024-02-12 10:59:31  2024-02-12 10:59:54              22          NaN   
353  2024-02-12 16:53:38  2024-02-12 16:55:58             140          NaN   
354  2024-02-12 19:25:52  2024-02-12 19:26:08              16          NaN   
355  2024-02-13 17:21:32  2024-02-13 17:24:22             169          NaN   
390  2024-02-14 17:52:56  2024-02-14 17:57:44             288          NaN   
415  2024-02-21 09:11:19  2024-02-21 09:11:29              10          NaN   
416  2024-02-21 09:44:09  2024-02-21 09:44:13               4          NaN   
418  2024-02-21 10:42:38  2024-02-21 10:43:54              76          NaN   
420  2024-02-21 13:09:37  2024-02-21 13:10:11              34          NaN   
422  2024-02-21 13:16:48  2024-02-21 13:17:16              28          NaN   
431  2024-02-23 12:09:19  2024-02-23 12:09:31              11          NaN   
433  2024-02-25 13:25:12  2024-02-25 13:27:20             127          NaN   
435  2024-02-28 18:31:15  2024-02-28 18:32:19              64          NaN   

    member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
15                 NaN             NaN            NaN           NaN   
16                 NaN             NaN            NaN           NaN   
17                 NaN             NaN            NaN           NaN   
18                 NaN             NaN            NaN           NaN   
193                NaN             NaN            NaN           NaN   

In [13]:
part_org_dt.columns.get_loc('zip_secd')

103

In [15]:
# coding incomplete responses=777
part_org_dt.iloc[[15,16,17, 18, 193, 209, 212, 215, 218, 219, 221, 226, 233, 234, 237, 
                  238, 241, 268, 270, 294, 302, 303, 307, 310, 315, 324, 326, 329, 333, 337, 
                  338, 340, 345, 353, 354, 355, 390, 415, 416, 418, 420, 422, 431,433, 435], 3:104]= 777
part_org_dt.head(20)

start_date             end_date  duration(sec.)  \
0   2024-01-27 18:25:34  2024-01-27 19:38:43            4389   
1   2024-01-27 19:59:36  2024-01-27 20:14:00             864   
2   2024-01-27 20:49:31  2024-01-27 21:10:40            1268   
3   2024-01-27 21:21:20  2024-01-27 22:18:03            3403   
4   2024-01-28 06:46:54  2024-01-28 07:14:28            1653   
5   2024-01-28 08:26:25  2024-01-28 08:38:15             710   
6   2024-01-28 09:41:18  2024-01-28 09:56:25             907   
7   2024-01-28 10:49:01  2024-01-28 11:01:30             748   
8   2024-01-28 10:48:29  2024-01-28 11:14:55            1586   
9   2024-01-28 11:29:51  2024-01-28 11:53:01            1390   
10  2024-01-28 13:26:35  2024-01-28 13:53:59            1644   
11  2024-01-28 15:59:20  2024-01-28 16:20:49            1288   
12  2024-01-29 20:04:54  2024-01-29 20:29:45            1490   
13  2024-01-23 12:47:05  2024-01-23 12:51:49             284   
14  2024-01-31 15:01:06  2024-01-31 15:25:27            1460   
15  2024-01-27 18:55:05  2024-01-27 18:55:14               8   
16  2024-01-27 19:04:05  2024-01-27 19:05:08              63   
17  2024-01-27 23:10:51  2024-01-27 23:11:05              13   
18  2024-01-28 08:01:49  2024-01-28 08:02:41              52   
19  2024-01-28 13:06:14  2024-01-28 13:09:13             179   

                                         organization member_stat_cswmhc  \
0                   Friends of Portsmouth Island only       Not a member   
1                   Friends of Portsmouth Island only     Current member   
2                   Friends of Portsmouth Island only     Current member   
3                   Friends of Portsmouth Island only       Not a member   
4                   Friends of Portsmouth Island only     Current member   
5   Neither, it was forwarded to me by someone I know       Not a member   
6                   Friends of Portsmouth Island only       Not a member   
7                   Friends of Portsmouth Island only       Prior member   
8                   Friends of Portsmouth Island only       Not a member   
9   Both Friends of Portsmouth Island and the Core...       Prior member   
10                  Friends of Portsmouth Island only       Not a member   
11                  Friends of Portsmouth Island only     Current member   
12                  Friends of Portsmouth Island only       Not a member   
13                  Friends of Portsmouth Island only     Current member   
14                  Friends of Portsmouth Island only     Current member   
15                                                777                777   
16                                                777                777   
17                                                777                777   
18                                                777                777   
19                  Friends of Portsmouth Island only     Current member   

   member_stat_fpi                                     hist_most_conn  \
0   Current member                                 Portsmouth Village   
1   Current member  Both Portsmouth Village and Cape Lookout Villa...   
2   Current member  The Coast Guard and Summer Cottages Area of Ca...   
3     Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
4   Current member                                 Portsmouth Village   
5     Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
6   Current member                                 Portsmouth Village   
7   Current member  Both Portsmouth Village and Cape Lookout Villa...   
8   Current member                                 Portsmouth Village   
9   Current member                                 Portsmouth Village   
10  Current member                                 Portsmouth Village   
11  Current member                                 Portsmouth Village   
12  Current member                                 Portsmouth Village   
13  Current member                               

In [17]:
# get location of the column 
part_org_dt.columns.get_loc('cons_mgt_bld_surv')

55

In [19]:
# pd.set_option('display.max_rows', None)
# find the row index 
part_org_dt.loc[part_org_dt['cons_mgt_bld_surv']== 'No']

start_date             end_date  duration(sec.)  \
1    2024-01-27 19:59:36  2024-01-27 20:14:00             864   
5    2024-01-28 08:26:25  2024-01-28 08:38:15             710   
22   2024-02-06 08:01:19  2024-02-06 08:14:42             802   
31   2024-02-06 08:28:55  2024-02-06 08:42:46             831   
33   2024-02-06 08:36:20  2024-02-06 08:43:45             445   
..                   ...                  ...             ...   
403  2024-02-23 06:52:10  2024-02-23 07:05:23             793   
407  2024-02-24 13:07:24  2024-02-24 13:11:12             228   
409  2024-02-25 09:45:25  2024-02-25 09:59:16             831   
412  2024-02-26 10:13:20  2024-02-26 10:24:02             642   
430  2024-03-01 07:43:03  2024-03-01 08:10:56            1672   

                                          organization member_stat_cswmhc  \
1                    Friends of Portsmouth Island only     Current member   
5    Neither, it was forwarded to me by someone I know       Not a member   
22   Core Sound Waterfowl Museum & Heritage Center ...     Current member   
31   Core Sound Waterfowl Museum & Heritage Center ...       Prior member   
33   Core Sound Waterfowl Museum & Heritage Center ...     Current member   
..                                                 ...                ...   
403  Core Sound Waterfowl Museum & Heritage Center ...     Current member   
407                  Friends of Portsmouth Island only                NaN   
409  Core Sound Waterfowl Museum & Heritage Center ...     Current member   
412  Neither, it was forwarded to me by someone I know     Current member   
430  Core Sound Waterfowl Museum & Heritage Center ...     Current member   

    member_stat_fpi                                     hist_most_conn  \
1    Current member  Both Portsmouth Village and Cape Lookout Villa...   
5      Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
22     Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
31     Not a member                        All of Cape Lookout Village   
33     Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
..              ...                                                ...   
403    Not a member                        All of Cape Lookout Village   
407  Current member                                 Portsmouth Village   
409    Not a member  The Cape Lookout Lighthouse Area of Cape Looko...   
412             NaN                                 Portsmouth Village   
430             NaN  The Cape Lookout Lighthouse Area of Cape Looko...   

                                         rec_most_conn  \
1    I don't feel connected to any of the recreatio...   
5                                           Cape Point   
22                                          Cape Point   
31                                          Cape Point   
33            All of the recreation areas listed above   
..                                                 ...   
403                                  Shackleford Banks   
407                                  Portsmouth Island   
409                                  Shackleford Banks   
412                                  Shackleford Banks   
430                                         Core Banks   

                   calo_part_me           ident_calo_strong  ... last_vist_yr  \
1                         Agree                       Agree  ...       2005.0   
5                         Agree                       Agree  ...       2023.0   
22                        Agree                       Agree  ...       2020.0   
31               Strongly agree              Strongly agree  ...       2023.0   
33                        Agree                       Agree  ...       2023.0   
..                          ...                         ...  ...          ...   
403              Strongly agree              Strongly agree  ...       2023.0   
407  Neither agree nor disagree  Neither agree nor disagree  ...       202

In [21]:
part_org_dt.columns.get_loc('stp_invst_dest<25%')

91

In [23]:
# coding incomplete responses due to skip logic answer 'No' = 222

part_org_dt.iloc[[1, 5, 22,27, 31,33, 34, 36, 39, 42, 44, 46, 50, 52, 56, 72, 77, 
                  78, 81, 82, 88, 90, 96, 99, 100, 101, 102,103, 117, 120, 121, 123, 
                  130, 133, 137, 139, 142, 143, 145, 146, 155, 160, 166, 168,169, 171, 172, 
                  181, 182,183, 187, 188, 189, 190, 191, 200, 204, 244, 249, 251, 253, 260, 
                  261, 262, 263, 265, 272, 278, 283, 284, 292, 293, 296, 359, 366, 368, 371, 
                  376, 380, 401, 403, 407, 409, 412, 430], 56:92]= 222
part_org_dt.head()

start_date             end_date  duration(sec.)  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653   

                        organization member_stat_cswmhc member_stat_fpi  \
0  Friends of Portsmouth Island only       Not a member  Current member   
1  Friends of Portsmouth Island only     Current member  Current member   
2  Friends of Portsmouth Island only     Current member  Current member   
3  Friends of Portsmouth Island only       Not a member    Not a member   
4  Friends of Portsmouth Island only     Current member  Current member   

                                      hist_most_conn  \
0                                 Portsmouth Village   
1  Both Portsmouth Village and Cape Lookout Villa...   
2  The Coast Guard and Summer Cottages Area of Ca...   
3  The Cape Lookout Lighthouse Area of Cape Looko...   
4                                 Portsmouth Village   

                                       rec_most_conn    calo_part_me  \
0           All of the recreation areas listed above           Agree   
1  I don't feel connected to any of the recreatio...           Agree   
2                                  Shackleford Banks  Strongly agree   
3                                         Core Banks  Strongly agree   
4                                  Portsmouth Island           Agree   

  ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv      vist_freq12_pv  \
0             Agree  ...       2023.0  More than 12 times            10 times   
1             Agree  ...       2005.0             0 times             0 times   
2    Strongly agree  ...       2023.0             6 times             0 times   
3    Strongly agree  ...       2023.0  More than 12 times  More than 12 times   
4             Agree  ...       2023.0              1 time             2 times   

       vist_freq12_pv vist_freq12_other  \
0  More than 12 times          10 times   
1             0 times           0 times   
2             0 times           6 times   
3             0 times           0 times   
4             2 times            1 time   

                                       own_occup_les my_rltv_own yes_we_own  \
0                                                 No         NaN        NaN   
1                                                 No         NaN        NaN   
2                                                 No         NaN        NaN   
3  No but I have visited people when they lived t...         NaN        NaN   
4  No but I have visited people when they lived t...         NaN        NaN   

  zip_prim zip_secd  
0    27019      NaN  
1    27603  28524.0  
2    28516      NaN  
3    28516      NaN  
4    27253      NaN  

[5 rows x 104 columns]

In [25]:
part_org_dt.columns.get_loc('calo_part_me')

8

In [27]:
# find the row index 
part_org_dt.loc[part_org_dt['calo_part_me']== '999']

Empty DataFrame
Columns: [start_date, end_date, duration(sec.), organization, member_stat_cswmhc, member_stat_fpi, hist_most_conn, rec_most_conn, calo_part_me, ident_calo_strong, dosnt_matter_calo, calo_uncompare, few_know_calo_lkme, fam_livhood_calo, fam_memry_calo, comm_hist_calo, locl_econ_calo, imp_nation_hist, imp_futr_gen, char_locl_comm, feel_comm_prd, comm_together, spec_plc_fam, my_hert_prid, fam_bond_locl_comm, toursm_incm, stabl_locl_econ, uniq_his_reg, uniq_locl_comm, imp_stry_past, imp_interptv_commnica, accessibility, hist_bld_rem, ablty_lrn_hist, ablty_rec_trd_area, all_chng_expr, visit_>75%_yr, visit_~50%_yr, visit_<25%_yr, no_accss, >75%_bld_rem_fr2018, ~50%_bld_rem_fr2018, <25%_bld_rem_fr2018, no_bld_rem_fr2018, visit_hrkrs_lrn_hdist_ph&v, visit_hrkrs_lrn_ppl_ph&v, visit_lrn_hdist_vr, lrn_ppl_bk, recr>75%_unchng, recr~50%_unchng, recr<25%_unchng, recr_no_unchng, bld_rem vs visit_accss, bld_rem vs lrn_bld, vist_accss vs lrn_bld, cons_mgt_bld_surv, oral_hist_calo, high_tech_calo, elev_st_calo, mov_st_calo, swall_calo, use_res_mat_calo, remv_prt_calo, let_go_calo, remv_st_calo, now_pstm_rcvr_calo, now_pstm_ret_calo, 2035_pstm_rcvr_calo, 2035_pstm_ret_calo, 2045_pstm_rcvr_calo, 2045_pstm_ret_calo, pstm_recvr vs pstm_retn, prsrv_fulnds vs adpt_fulnds, prsrv_fulnds vs trns_fulnds, adpt_fulnds vs trns_fulnds, 2035 prsrv_fulnds vs adpt_fulnds, 2035 prsrv_fulnds vs trns_fulnds, 2035 adpt_fulnds vs trns_fulnds, 2035 prsrv_fulnds vs adpt_fulnds, 2045 prsrv_fulnds vs trns_fulnds, 2045 adpt_fulnds vs trns_fulnds, excpt_lhs_any_other_45, stp_invst_accss>75%, stp_invst_accss~50%, stp_invst_accss<25%, stp_invst_accss_no, stp_invst_rem>75%, stp_invst_rem~50%, stp_invst_rem<25%, stp_invst_dest>75%, stp_invst_dest~50%, stp_invst_dest<25%, b_yr, 1st_vist_yr, last_vist_yr, vist_freq12_lths_cv, vist_freq12_pv, vist_freq12_pv, vist_freq12_other, own_occup_les, ...]
Index: []

[0 rows x 104 columns]

In [29]:
# coding incomplete becasuse respondents stopped after answeirng 'organization' question = 555
part_org_dt.iloc[[19, 207, 210, 216, 227, 230, 232, 236, 240, 269, 285, 301, 314, 321, 328, 330, 331,
                  336, 364, 397, 413, 423, 424, 432], 8:104]= 555
part_org_dt.head()

start_date             end_date  duration(sec.)  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653   

                        organization member_stat_cswmhc member_stat_fpi  \
0  Friends of Portsmouth Island only       Not a member  Current member   
1  Friends of Portsmouth Island only     Current member  Current member   
2  Friends of Portsmouth Island only     Current member  Current member   
3  Friends of Portsmouth Island only       Not a member    Not a member   
4  Friends of Portsmouth Island only     Current member  Current member   

                                      hist_most_conn  \
0                                 Portsmouth Village   
1  Both Portsmouth Village and Cape Lookout Villa...   
2  The Coast Guard and Summer Cottages Area of Ca...   
3  The Cape Lookout Lighthouse Area of Cape Looko...   
4                                 Portsmouth Village   

                                       rec_most_conn    calo_part_me  \
0           All of the recreation areas listed above           Agree   
1  I don't feel connected to any of the recreatio...           Agree   
2                                  Shackleford Banks  Strongly agree   
3                                         Core Banks  Strongly agree   
4                                  Portsmouth Island           Agree   

  ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv      vist_freq12_pv  \
0             Agree  ...       2023.0  More than 12 times            10 times   
1             Agree  ...       2005.0             0 times             0 times   
2    Strongly agree  ...       2023.0             6 times             0 times   
3    Strongly agree  ...       2023.0  More than 12 times  More than 12 times   
4             Agree  ...       2023.0              1 time             2 times   

       vist_freq12_pv vist_freq12_other  \
0  More than 12 times          10 times   
1             0 times           0 times   
2             0 times           6 times   
3             0 times           0 times   
4             2 times            1 time   

                                       own_occup_les my_rltv_own yes_we_own  \
0                                                 No         NaN        NaN   
1                                                 No         NaN        NaN   
2                                                 No         NaN        NaN   
3  No but I have visited people when they lived t...         NaN        NaN   
4  No but I have visited people when they lived t...         NaN        NaN   

  zip_prim zip_secd  
0    27019      NaN  
1    27603  28524.0  
2    28516      NaN  
3    28516      NaN  
4    27253      NaN  

[5 rows x 104 columns]

In [31]:
# coding missing value= 999
part_org_dt.fillna('999', inplace=True)
part_org_dt.head()

/var/folders/1r/vrmrp_9j4_q5k7dqlkm0wk6m0000gq/T/ipykernel_6784/3467628857.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '999' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  part_org_dt.fillna('999', inplace=True)
/var/folders/1r/vrmrp_9j4_q5k7dqlkm0wk6m0000gq/T/ipykernel_6784/3467628857.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  part_org_dt.fillna('999', inplace=True)


start_date             end_date  duration(sec.)  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653   

                        organization member_stat_cswmhc member_stat_fpi  \
0  Friends of Portsmouth Island only       Not a member  Current member   
1  Friends of Portsmouth Island only     Current member  Current member   
2  Friends of Portsmouth Island only     Current member  Current member   
3  Friends of Portsmouth Island only       Not a member    Not a member   
4  Friends of Portsmouth Island only     Current member  Current member   

                                      hist_most_conn  \
0                                 Portsmouth Village   
1  Both Portsmouth Village and Cape Lookout Villa...   
2  The Coast Guard and Summer Cottages Area of Ca...   
3  The Cape Lookout Lighthouse Area of Cape Looko...   
4                                 Portsmouth Village   

                                       rec_most_conn    calo_part_me  \
0           All of the recreation areas listed above           Agree   
1  I don't feel connected to any of the recreatio...           Agree   
2                                  Shackleford Banks  Strongly agree   
3                                         Core Banks  Strongly agree   
4                                  Portsmouth Island           Agree   

  ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv      vist_freq12_pv  \
0             Agree  ...       2023.0  More than 12 times            10 times   
1             Agree  ...       2005.0             0 times             0 times   
2    Strongly agree  ...       2023.0             6 times             0 times   
3    Strongly agree  ...       2023.0  More than 12 times  More than 12 times   
4             Agree  ...       2023.0              1 time             2 times   

       vist_freq12_pv vist_freq12_other  \
0  More than 12 times          10 times   
1             0 times           0 times   
2             0 times           6 times   
3             0 times           0 times   
4             2 times            1 time   

                                       own_occup_les my_rltv_own yes_we_own  \
0                                                 No         999        999   
1                                                 No         999        999   
2                                                 No         999        999   
3  No but I have visited people when they lived t...         999        999   
4  No but I have visited people when they lived t...         999        999   

  zip_prim zip_secd  
0    27019      999  
1    27603  28524.0  
2    28516      999  
3    28516      999  
4    27253      999  

[5 rows x 104 columns]

In [33]:
#pd.set_option('display.max_rows', None)
part_org_dt[['start_date', 'cons_mgt_bld_surv','oral_hist_calo' ]]

start_date cons_mgt_bld_surv  oral_hist_calo
0    2024-01-27 18:25:34               Yes  Somewhat agree
1    2024-01-27 19:59:36                No             222
2    2024-01-27 20:49:31               Yes  Strongly agree
3    2024-01-27 21:21:20               Yes  Strongly agree
4    2024-01-28 06:46:54               Yes  Strongly agree
..                   ...               ...             ...
431  2024-02-23 12:09:19               777             777
432  2024-02-24 11:51:35               555             555
433  2024-02-25 13:25:12               777             777
434  2024-02-25 13:52:15               999             999
435  2024-02-28 18:31:15               777             777

[436 rows x 3 columns]

In [39]:
# removing special charactes of string values of the followingt columns:

part_org_dt['accessibility'] = part_org_dt['accessibility'].str.replace("\W", '', regex=True)
part_org_dt['hist_bld_rem'] = part_org_dt['hist_bld_rem'].str.replace("\W", '', regex=True)
part_org_dt['ablty_lrn_hist'] = part_org_dt['ablty_lrn_hist'].str.replace("\W", '', regex=True)
part_org_dt['ablty_rec_trd_area'] = part_org_dt['ablty_rec_trd_area'].str.replace("\W", '', regex=True)
part_org_dt['all_chng_expr'] = part_org_dt['all_chng_expr'].str.replace("\W", '', regex=True)

part_org_dt['visit_>75%_yr'] = part_org_dt['visit_>75%_yr'].str.replace("\W", '', regex=True)
part_org_dt['visit_~50%_yr'] = part_org_dt['visit_~50%_yr'].str.replace("\W", '', regex=True)
part_org_dt['visit_<25%_yr'] = part_org_dt['visit_<25%_yr'].str.replace("\W", '', regex=True)
part_org_dt['no_accss'] = part_org_dt['no_accss'].str.replace("\W", '', regex=True)

part_org_dt['>75%_bld_rem_fr2018'] = part_org_dt['>75%_bld_rem_fr2018'].str.replace("\W", '', regex=True)
part_org_dt['~50%_bld_rem_fr2018'] = part_org_dt['~50%_bld_rem_fr2018'].str.replace("\W", '', regex=True)
part_org_dt['<25%_bld_rem_fr2018'] = part_org_dt['<25%_bld_rem_fr2018'].str.replace("\W", '', regex=True)
part_org_dt['no_bld_rem_fr2018'] = part_org_dt['no_bld_rem_fr2018'].str.replace("\W", '', regex=True)

part_org_dt['visit_hrkrs_lrn_hdist_ph&v']=part_org_dt['visit_hrkrs_lrn_hdist_ph&v'].str.replace("\W",'',regex=True)
part_org_dt['visit_hrkrs_lrn_ppl_ph&v']=part_org_dt['visit_hrkrs_lrn_ppl_ph&v'].str.replace("\W",'',regex=True)
part_org_dt['visit_lrn_hdist_vr']=part_org_dt['visit_lrn_hdist_vr'].str.replace("\W", '', regex=True)
part_org_dt['lrn_ppl_bk']=part_org_dt['lrn_ppl_bk'].str.replace("\W", '', regex=True)

part_org_dt['recr>75%_unchng'] = part_org_dt['recr>75%_unchng'].str.replace("\W", '', regex=True)
part_org_dt['recr~50%_unchng'] = part_org_dt['recr~50%_unchng'].str.replace("\W", '', regex=True)
part_org_dt['recr<25%_unchng'] = part_org_dt['recr<25%_unchng'].str.replace("\W", '', regex=True)
part_org_dt['recr_no_unchng'] = part_org_dt['recr_no_unchng'].str.replace("\W", '', regex=True)

In [41]:
# data code change 
prt_cldt2 = part_org_dt.replace(
    to_replace= ['Strongly disagree',
                'Disa​gree', 
                'Neither agree nor disagree',
                'Agree',
                'Strongly agree',
                
                'Stronglynegativeimpact', 
                'Somewhatnegativeimpact', 
                'Nochange',
                'Somewhatpositiveimpact',
                'Stronglypositiveimpact',
                 
                'Strongly disagree',
                'Somewhat disagree', 
                'Neutral',
                'Somewhat agree',
                'Strongly agree',
                
                'Friends of Portsmouth Island only',
                'Core Sound Waterfowl Museum & Heritage Center only',
                'Both Friends of Portsmouth Island and the Core Sound Waterfowl Museum & Heritage Center',
                'Neither, it was forwarded to me by someone I know',
                
                'Current member',
                'Not a member',
                'Prior member',
                
                'Portsmouth Village', 
                'The Cape Lookout Lighthouse Area of Cape Lookout Village',
                'The Coast Guard and Summer Cottages Area of Cape Lookout Village',
                'All of Cape Lookout Village',
                'Both Portsmouth Village and Cape Lookout Village Equally',  
                'I do not feel connected to either Village',
                
                 'Yes', 'No',
                
                'Shackleford Banks',
                'Core Banks', 
                'Portsmouth Island',
                'Great Island', 
                'Cape Point', 
                "I don't feel connected to any of the recreation areas",
                'All of the recreation areas listed above',
                
               
                'Yes\n(please indicate in which year you last occupied the structure)',
                'No but I have visited people when they lived there',
                'Not me but my relatives have\n(please indicate in which year your family last occupied the building)'],
   
    value=['-2','-1', '0', '1', '2', 
           
          '-2','-1', '0', '1', '2',
           
           '-2','-1', '0', '1', '2',
          
          '1', '2', '3', '4',
          
          '2', '0', '1',
          
          '1', '2', '3', '4', '5', '6',
          
           '1', '0',
           
           '1', '2', '3', '4', '5', '6', '7',
          
          '1', '2', '3' ])


prt_cldt2


start_date             end_date  duration(sec.) organization  \
0    2024-01-27 18:25:34  2024-01-27 19:38:43            4389            1   
1    2024-01-27 19:59:36  2024-01-27 20:14:00             864            1   
2    2024-01-27 20:49:31  2024-01-27 21:10:40            1268            1   
3    2024-01-27 21:21:20  2024-01-27 22:18:03            3403            1   
4    2024-01-28 06:46:54  2024-01-28 07:14:28            1653            1   
..                   ...                  ...             ...          ...   
431  2024-02-23 12:09:19  2024-02-23 12:09:31              11          777   
432  2024-02-24 11:51:35  2024-02-24 11:56:51             315            1   
433  2024-02-25 13:25:12  2024-02-25 13:27:20             127          777   
434  2024-02-25 13:52:15  2024-02-25 13:57:22             306            2   
435  2024-02-28 18:31:15  2024-02-28 18:32:19              64          777   

    member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
0                    0               2              1             7   
1                    2               2              5             6   
2                    2               2              3             1   
3                    0               0              2             2   
4                    2               2              1             3   
..                 ...             ...            ...           ...   
431                777             777            777           777   
432                  2               2              1             3   
433                777             777            777           777   
434                  2             999              6             2   
435                777             777            777           777   

    calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
0              1                 1  ...       2023.0  More than 12 times   
1              1                 1  ...       2005.0             0 times   
2              2                 2  ...       2023.0             6 times   
3              2                 2  ...       2023.0  More than 12 times   
4              1                 1  ...       2023.0              1 time   
..           ...               ...  ...          ...                 ...   
431          777               777  ...        777.0                 777   
432          555               555  ...        555.0                 555   
433          777               777  ...        777.0                 777   
434            0                 0  ...          999                 999   
435          777               777  ...        777.0                 777   

         vist_freq12_pv      vist_freq12_pv vist_freq12_other own_occup_les  \
0              10 times  More than 12 times          10 times             0   
1               0 times             0 times           0 times             0   
2               0 times             0 times           6 times             0   
3    More than 12 times             0 times           0 times             2   
4               2 times             2 times            1 time             2   
..                  ...                 ...               ...           ...   
431                 777                 777               777           777   
432                 555                 555               555           555   
433                 777                 777               777           777   
434                 999                 999               999           999   
435                 777                 777               777           777   

    my_rltv_own yes_we_own zip_prim zip_secd  
0           999        999    27019      999  
1           999        999    27603  28524.0  
2           999        999    28516      999  
3           999        999    28516      999  
4           999        999    27253      999  
..          ...        ...      ...      ...  
431       777.0      777.0      7

In [43]:
# coding incomplete responses due to skip logic answer 'No' = 222

prt_cldt2.iloc[[1, 5, 22,27, 31,33, 34, 36, 39, 42, 44, 46, 50, 52, 56, 72, 77, 
                  78, 81, 82, 88, 90, 96, 99, 100, 101, 102,103, 117, 120, 121, 123, 
                  130, 133, 137, 139, 142, 143, 145, 146, 155, 160, 166, 168,169, 171, 172, 
                  181, 182,183, 187, 188, 189, 190, 191, 200, 204, 244, 249, 251, 253, 260, 
                  261, 262, 263, 265, 272, 278, 283, 284, 292, 293, 296, 359, 366, 368, 371, 
                  376, 380, 401, 403, 407, 409, 412, 430], 56:92]= 222
prt_cldt2.head()

start_date             end_date  duration(sec.) organization  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389            1   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864            1   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268            1   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403            1   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653            1   

  member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
0                  0               2              1             7   
1                  2               2              5             6   
2                  2               2              3             1   
3                  0               0              2             2   
4                  2               2              1             3   

  calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
0            1                 1  ...       2023.0  More than 12 times   
1            1                 1  ...       2005.0             0 times   
2            2                 2  ...       2023.0             6 times   
3            2                 2  ...       2023.0  More than 12 times   
4            1                 1  ...       2023.0              1 time   

       vist_freq12_pv      vist_freq12_pv vist_freq12_other own_occup_les  \
0            10 times  More than 12 times          10 times             0   
1             0 times             0 times           0 times             0   
2             0 times             0 times           6 times             0   
3  More than 12 times             0 times           0 times             2   
4             2 times             2 times            1 time             2   

  my_rltv_own yes_we_own zip_prim zip_secd  
0         999        999    27019      999  
1         999        999    27603  28524.0  
2         999        999    28516      999  
3         999        999    28516      999  
4         999        999    27253      999  

[5 rows x 104 columns]

In [45]:
# coding incomplete becasuse respondents stopped after answeirng 'organization' question = 555
prt_cldt2.iloc[[19, 207, 210, 216, 227, 230, 232, 236, 240, 269, 285, 301, 314, 321, 328, 330, 331,
                  336, 364, 397, 413, 423, 424, 432], 8:104]= 555
prt_cldt2.head()

start_date             end_date  duration(sec.) organization  \
0  2024-01-27 18:25:34  2024-01-27 19:38:43            4389            1   
1  2024-01-27 19:59:36  2024-01-27 20:14:00             864            1   
2  2024-01-27 20:49:31  2024-01-27 21:10:40            1268            1   
3  2024-01-27 21:21:20  2024-01-27 22:18:03            3403            1   
4  2024-01-28 06:46:54  2024-01-28 07:14:28            1653            1   

  member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
0                  0               2              1             7   
1                  2               2              5             6   
2                  2               2              3             1   
3                  0               0              2             2   
4                  2               2              1             3   

  calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
0            1                 1  ...       2023.0  More than 12 times   
1            1                 1  ...       2005.0             0 times   
2            2                 2  ...       2023.0             6 times   
3            2                 2  ...       2023.0  More than 12 times   
4            1                 1  ...       2023.0              1 time   

       vist_freq12_pv      vist_freq12_pv vist_freq12_other own_occup_les  \
0            10 times  More than 12 times          10 times             0   
1             0 times             0 times           0 times             0   
2             0 times             0 times           6 times             0   
3  More than 12 times             0 times           0 times             2   
4             2 times             2 times            1 time             2   

  my_rltv_own yes_we_own zip_prim zip_secd  
0         999        999    27019      999  
1         999        999    27603  28524.0  
2         999        999    28516      999  
3         999        999    28516      999  
4         999        999    27253      999  

[5 rows x 104 columns]

In [47]:
# coding incomplete responses=777
prt_cldt2.iloc[[15,16,17, 18, 193, 209, 212, 215, 218, 219, 221, 226, 233, 234, 237, 
                  238, 241, 268, 270, 294, 302, 303, 307, 310, 315, 324, 326, 329, 333, 337, 
                  338, 340, 345, 353, 354, 355, 390, 415, 416, 418, 420, 422, 431,433, 435], 3:104]= 777
prt_cldt2.head(20)

start_date             end_date  duration(sec.) organization  \
0   2024-01-27 18:25:34  2024-01-27 19:38:43            4389            1   
1   2024-01-27 19:59:36  2024-01-27 20:14:00             864            1   
2   2024-01-27 20:49:31  2024-01-27 21:10:40            1268            1   
3   2024-01-27 21:21:20  2024-01-27 22:18:03            3403            1   
4   2024-01-28 06:46:54  2024-01-28 07:14:28            1653            1   
5   2024-01-28 08:26:25  2024-01-28 08:38:15             710            4   
6   2024-01-28 09:41:18  2024-01-28 09:56:25             907            1   
7   2024-01-28 10:49:01  2024-01-28 11:01:30             748            1   
8   2024-01-28 10:48:29  2024-01-28 11:14:55            1586            1   
9   2024-01-28 11:29:51  2024-01-28 11:53:01            1390            3   
10  2024-01-28 13:26:35  2024-01-28 13:53:59            1644            1   
11  2024-01-28 15:59:20  2024-01-28 16:20:49            1288            1   
12  2024-01-29 20:04:54  2024-01-29 20:29:45            1490            1   
13  2024-01-23 12:47:05  2024-01-23 12:51:49             284            1   
14  2024-01-31 15:01:06  2024-01-31 15:25:27            1460            1   
15  2024-01-27 18:55:05  2024-01-27 18:55:14               8          777   
16  2024-01-27 19:04:05  2024-01-27 19:05:08              63          777   
17  2024-01-27 23:10:51  2024-01-27 23:11:05              13          777   
18  2024-01-28 08:01:49  2024-01-28 08:02:41              52          777   
19  2024-01-28 13:06:14  2024-01-28 13:09:13             179            1   

   member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
0                   0               2              1             7   
1                   2               2              5             6   
2                   2               2              3             1   
3                   0               0              2             2   
4                   2               2              1             3   
5                   0               0              2             5   
6                   0               2              1             6   
7                   1               2              5             7   
8                   0               2              1             2   
9                   1               2              1             3   
10                  0               2              1             7   
11                  2               2              1             3   
12                  0               2              1             3   
13                  2               2              1             1   
14                  2               2              1             2   
15                777             777            777           777   
16                777             777            777           777   
17                777             777            777           777   
18                777             777            777           777   
19                  2               0              2             7   

   calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
0             1                 1  ...       2023.0  More than 12 times   
1             1                 1  ...       2005.0             0 times   
2             2                 2  ...       2023.0             6 times   
3             2                 2  ...       2023.0  More than 12 times   
4             1                 1  ...       2023.0              1 time   
5             1                 1  ...       2023.0            10 times   
6             1                 0  ...       2023.0             0 times   
7             2                 1  ...       2023.0              1 time   
8             1                 1  ...       2019.0             0 times   
9             2                 2  ...       2023.0             0 times   
10            2                 2  ...       2023.0              1 time   
11            2         

In [51]:
#pd.set_option('display.max_rows', None)

# Filter data by removing the test responses before sending the survey
prt_cldt2a= prt_cldt2[(part_org_dt.start_date > '2024-01-31 18:26:49')]
prt_cldt2a

start_date             end_date  duration(sec.) organization  \
21   2024-02-06 08:02:23  2024-02-06 08:13:41             678            1   
22   2024-02-06 08:01:19  2024-02-06 08:14:42             802            2   
23   2024-02-06 08:04:59  2024-02-06 08:19:38             879            3   
24   2024-02-06 08:07:31  2024-02-06 08:20:02             750            2   
25   2024-02-06 08:01:35  2024-02-06 08:21:10            1175            2   
..                   ...                  ...             ...          ...   
431  2024-02-23 12:09:19  2024-02-23 12:09:31              11          777   
432  2024-02-24 11:51:35  2024-02-24 11:56:51             315            1   
433  2024-02-25 13:25:12  2024-02-25 13:27:20             127          777   
434  2024-02-25 13:52:15  2024-02-25 13:57:22             306            2   
435  2024-02-28 18:31:15  2024-02-28 18:32:19              64          777   

    member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
21                   0               2              1             3   
22                   2               0              2             5   
23                   2               2              5             7   
24                   1               0              4             7   
25                   2               0              4             7   
..                 ...             ...            ...           ...   
431                777             777            777           777   
432                  2               2              1             3   
433                777             777            777           777   
434                  2             999              6             2   
435                777             777            777           777   

    calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
21             1                 1  ...       2021.0             0 times   
22             1                 1  ...       2020.0             0 times   
23             2                 2  ...       2023.0  More than 12 times   
24             2                 2  ...       2023.0             4 times   
25             2                 2  ...       2023.0  More than 12 times   
..           ...               ...  ...          ...                 ...   
431          777               777  ...          777                 777   
432          555               555  ...          555                 555   
433          777               777  ...          777                 777   
434            0                 0  ...          999                 999   
435          777               777  ...          777                 777   

         vist_freq12_pv vist_freq12_pv vist_freq12_other own_occup_les  \
21              0 times        0 times           0 times             0   
22              0 times        0 times            1 time             0   
23              5 times        3 times          10 times             1   
24              2 times         1 time           5 times             0   
25   More than 12 times        0 times           0 times             2   
..                  ...            ...               ...           ...   
431                 777            777               777           777   
432                 555            555               555           555   
433                 777            777               777           777   
434                 999            999               999           999   
435                 777            777               777           777   

    my_rltv_own yes_we_own zip_prim zip_secd  
21          999        999    28584      999  
22          999        999    24503  28531.0  
23          999     1995.0    27591  28579.0  
24          999        999    28510      999  
25          999        999    28528      999  
..          ...        ...      ...      ...  
431         777        777      777      777  
432         555        555      555      555  

<p style="color:blue;font-weight:500;font-size:16px; text-align: center;"> Cleaned Data File Save </p> 

In [53]:
prt_cldt2a.to_excel('part_surv24_clnd.xlsx')

In [55]:
dt_cl= pd.read_excel('part_surv24_clnd.xlsx')
pd.crosstab(index=dt_cl['accessibility'], columns='count')

col_0          count
accessibility       
-2                21
-1               108
 0               146
 1                12
 2                10
 555              23
 777              41
 999              52

In [60]:
pd.crosstab(part_org_dt['accessibility'], columns='ct')

col_0                        ct
accessibility                  
555                          24
777                          45
999                          52
No change                   153
Somewhat negative impact    112
Somewhat positive impact     12
Strongly negative impact\n   26
Strongly positive impact     12

### Fequency and % calculation of own/occup

In [41]:
# frequencey of all data including before feb.06 (survey sending date), N=436
pd.crosstab(index=part_org_dt['own_occup_les'], columns='count')

col_0                                               count
own_occup_les                                            
555                                                    24
777                                                    45
999                                                    75
No                                                    212
No but I have visited people when they lived there     23
Not me but my relatives have\n(please indicate ...     31
Yes\n(please indicate in which year you last oc...     26

In [43]:
# % of all data including before feb.06 (survey sending date), N=436
pd.crosstab(index=part_org_dt['own_occup_les'], columns='%', normalize= 'all').round(4)*100

col_0                                                   %
own_occup_les                                            
555                                                  5.50
777                                                 10.32
999                                                 17.20
No                                                  48.62
No but I have visited people when they lived there   5.28
Not me but my relatives have\n(please indicate ...   7.11
Yes\n(please indicate in which year you last oc...   5.96

In [75]:
# frequency of data from the Feb. 06 (survey sending date), N= 413
# 0= No;    1= Yes.  ; 3= No but I have visited people when they lived there;   4= Not me but my relatives have

pd.crosstab(index=prt_cldt2a['own_occup_les'], columns='count')

col_0          count
own_occup_les       
0                205
1                 24
2                 21
3                 28
555               23
777               41
999               71

<p Style= 'color: blue; font-size: 16px; font-color: 'blue'> -Incomplete responses due to error in organization Q. = 777 </p>
<p Style= 'color: blue;font-size: 16px'> -Incomplete responses due to stop answering after organization Q.= 555 </p>
<p Style= 'color: blue;font-size: 16px'> -Missing value= 999 </p>
<p Style= 'color: blue;font-size: 16px'> -Missing value due to jump logic (Ans.-NO)= 222 </p>




In [73]:
# % of data from the Feb. 06 (survey sending date), N= 413

# 0= No;    1= Yes.  ; 3= No but I have visited people when they lived there;   4= Not me but my relatives have

pd.crosstab(index=prt_cldt2a['own_occup_les'], columns='%', normalize= 'all').round(4)*100

col_0              %
own_occup_les       
0              49.64
1               5.81
2               5.08
3               6.78
555             5.57
777             9.93
999            17.19

In [79]:
prt_cldt2a['own_occup_les']= pd.to_numeric(prt_cldt2a['own_occup_les'])

/var/folders/1r/vrmrp_9j4_q5k7dqlkm0wk6m0000gq/T/ipykernel_6784/4308567.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prt_cldt2a['own_occup_les']= pd.to_numeric(prt_cldt2a['own_occup_les'])


In [81]:
# % of data excluding 555, 777, 999 (survey sending date), N= 278

# 0= No;    1= Yes.  ; 3= No but I have visited people when they lived there;   4= Not me but my relatives have

prt_cldt3=prt_cldt2a[(prt_cldt2a['own_occup_les'] < 555)]
prt_cldt3

start_date             end_date  duration(sec.) organization  \
21   2024-02-06 08:02:23  2024-02-06 08:13:41             678            1   
22   2024-02-06 08:01:19  2024-02-06 08:14:42             802            2   
23   2024-02-06 08:04:59  2024-02-06 08:19:38             879            3   
24   2024-02-06 08:07:31  2024-02-06 08:20:02             750            2   
25   2024-02-06 08:01:35  2024-02-06 08:21:10            1175            2   
..                   ...                  ...             ...          ...   
409  2024-02-25 09:45:25  2024-02-25 09:59:16             831            2   
410  2024-02-25 12:01:53  2024-02-25 12:44:34            2561            4   
411  2024-02-25 23:28:05  2024-02-25 23:48:15            1209            1   
412  2024-02-26 10:13:20  2024-02-26 10:24:02             642            4   
430  2024-03-01 07:43:03  2024-03-01 08:10:56            1672            2   

    member_stat_cswmhc member_stat_fpi hist_most_conn rec_most_conn  \
21                   0               2              1             3   
22                   2               0              2             5   
23                   2               2              5             7   
24                   1               0              4             7   
25                   2               0              4             7   
..                 ...             ...            ...           ...   
409                  2               0              2             1   
410                  2             999              4             2   
411                  0               2              5             7   
412                  2             999              1             1   
430                  2             999              2             2   

    calo_part_me ident_calo_strong  ... last_vist_yr vist_freq12_lths_cv  \
21             1                 1  ...       2021.0             0 times   
22             1                 1  ...       2020.0             0 times   
23             2                 2  ...       2023.0  More than 12 times   
24             2                 2  ...       2023.0             4 times   
25             2                 2  ...       2023.0  More than 12 times   
..           ...               ...  ...          ...                 ...   
409            2                 2  ...       2023.0            10 times   
410            2                 2  ...       2023.0  More than 12 times   
411            2                 2  ...       2023.0             2 times   
412            1                 1  ...       2023.0              1 time   
430            1                 0  ...       2012.0             0 times   

         vist_freq12_pv vist_freq12_pv   vist_freq12_other own_occup_les  \
21              0 times        0 times             0 times             0   
22              0 times        0 times              1 time             0   
23              5 times        3 times            10 times             1   
24              2 times         1 time             5 times             0   
25   More than 12 times        0 times             0 times             2   
..                  ...            ...                 ...           ...   
409              1 time        0 times  More than 12 times             3   
410             2 times        0 times  More than 12 times             1   
411             2 times        5 times             3 times             0   
412              1 time         1 time  More than 12 times             0   
430             0 times        0 times             0 times             1   

    my_rltv_own yes_we_own zip_prim zip_secd  
21          999        999    28584      999  
22          999        999    24503  28531.0  
23          999     1995.0    27591  28579.0  
24          999        999    28510      999  
25          999        999    28528      999  
..          ...        ...      ...      ...  
409      1960.0        999    28562  28531.0  
410         999     19

In [83]:
# frequencey of all data including before feb.06 (survey sending date), N= 278
pd.crosstab(index=prt_cldt3['own_occup_les'], columns='count')

col_0          count
own_occup_les       
0                205
1                 24
2                 21
3                 28

In [85]:
# % of all data including before feb.06 (survey sending date), N= 278
pd.crosstab(index=prt_cldt3['own_occup_les'], columns='%', normalize= 'all').round(4)*100

col_0              %
own_occup_les       
0              73.74
1               8.63
2               7.55
3              10.07

In [87]:
# discuss with Erin
# codes 555 and 222
# new count and % calculation
# Yes, No coding into 1, 0 
# Own/occup codes 0,1,2,3

# Erin's Feedback: To Do List
### > Exclude the data with start date before Feb 06
### > Code missing value as '999'; not completed as '777'; Ans. Org. Q only: 555; Jump logic: 222
### > Code the slider responses to '0' if theres no data recorded. This may be because people did not move the slides as they thought it should be zero. 
### > If someone did not answer the demographic questions, the response should still be considered valid data point. 
### > If someonw stopped answering after Q1.2, the data should be excluded. But frequencies of those cases needs to be reported. Initially the participants encoutnred some error to proceed after Q1.2, but it has been corrected on Feb 16.


<p style="text-align: center; font-size: 20px">*****THE END*****</p>